env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    rclone_config: "ENCRYPTED[84378bb65c63f2d8176c7aac3d1210e5c957dbe8ec383833510c6bcee32a7c2202b38de9b6bc7cc7463b9c8523a9e154]"
    CHATID: "ENCRYPTED[0a5446adacbe1648ea7b37f53530585d0b6c2ee8e567ff39bfafc9d0d27656df52cde0cd41c1811924ae11fb8d51dace]"
    API_BOT: "ENCRYPTED[00e2f1e3a03c85dac4bf5589eca9d707dc84df8aa13d722740e97cad07a5742397f55d9fdaaa9c4e8b458e83e16ceff0]"
task:
    name: MiDoNaSR
    timeout_in: 240m
    container:
      image: apon77/aosp:latest
      cpu: 16
      memory: 24G
    download_ccache_background_script:
      - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
